export const PROMPTS = [
  "Whose voice wasn’t heard today?",
  "What assumptions did I make?",
  "Did I interrupt or overlook someone’s contribution?",
  "Who did I advocate for today?",
  "What privilege did I benefit from today?",
  "Did I notice any exclusion? How did I respond?",
  "What did I learn from someone different to me?",
  "How did I show empathy today?",
  "What bias might have influenced my decisions?",
  "Who did I make feel seen or valued today?",
  "Did I challenge a stereotype or generalisation?",
  "What discomfort did I lean into today?",
  "How did I support someone’s wellbeing?",
  "What inclusive language did I use today?",
  "Did I create space for diverse perspectives?",
  "What feedback did I receive or give that built trust?",
  "How did I respond to someone’s lived experience?",
  "What microaggression did I notice or address?",
  "Who did I listen to without judgment today?",
  "What action did I take to be an ally?",
  "How did I make someone feel safe to speak up?",
  "What did I do to reduce barriers for others?",
  "Did I ask for consent before sharing someone’s story?",
  "What did I do to support accessibility today?",
  "How did I show up for someone in a moment of need?",
  "What inclusive practice did I model today?",
  "What did I do to build psychological safety?",
  "How did I use my influence to support equity?",
  "What did I do to learn more about a community I’m not part of?",
  "How did I make space for joy and celebration of difference?",
  "What will I do differently tomorrow?"
];
